import React from 'react';
import { InsightCard, HealthStatus } from '../types';
import { Lightbulb, ArrowRight, ShieldCheck, Zap, ChevronRight, PanelRightClose, PanelRightOpen, Eye } from 'lucide-react';

interface InsightPanelProps {
  insights: InsightCard[];
  isOpen: boolean;
  togglePanel: () => void;
}

export const InsightPanel: React.FC<InsightPanelProps> = ({ insights, isOpen, togglePanel }) => {
  return (
    <>
      {/* Toggle Button for when panel is closed */}
      {!isOpen && (
        <button 
          onClick={togglePanel}
          className="absolute right-0 top-24 bg-white border-l border-t border-b border-slate-200 p-2 rounded-l-xl shadow-sm text-slate-500 hover:text-blue-600 hover:bg-slate-50 z-30 transition-all hover:pr-3 hover:shadow-md"
          title="Open Insight Feed"
        >
          <PanelRightOpen size={20} />
        </button>
      )}

      <div 
        className={`
          bg-white border-l border-slate-200 h-full flex flex-col flex-shrink-0 shadow-[-4px_0_24px_-12px_rgba(0,0,0,0.05)] z-20 transition-all duration-300 ease-in-out
          ${isOpen ? 'w-[400px] translate-x-0 opacity-100' : 'w-0 translate-x-full opacity-0 overflow-hidden'}
        `}
      >
        <div className="p-6 border-b border-slate-50 bg-slate-50/30 flex justify-between items-start">
          <div>
            <div className="flex items-center gap-2.5 mb-1.5">
              <div className="bg-amber-50 p-2 rounded-lg text-amber-500 ring-1 ring-amber-100">
                <Lightbulb size={18} className="fill-amber-400" />
              </div>
              <h2 className="font-bold text-slate-800 text-lg tracking-tight">Insight Feed</h2>
            </div>
            <p className="text-xs text-slate-500 font-medium pl-1">Prioritized items for review</p>
          </div>
          <button 
            onClick={togglePanel}
            className="text-slate-400 hover:text-slate-600 hover:bg-slate-100 p-2 rounded-lg transition-colors active:scale-95"
          >
            <PanelRightClose size={18} />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-6 space-y-5 bg-white">
          {/* Disclaimer Card */}
          <div className="bg-blue-50/50 border border-blue-100 rounded-lg p-3 flex gap-3">
             <div className="mt-0.5"><Eye size={14} className="text-blue-500" /></div>
             <div>
                <p className="text-[10px] text-blue-700 font-medium leading-tight">
                  <span className="font-bold">Human-in-the-Loop:</span> All insights generated by the system are recommendations intended for human review and decision-making.
                </p>
             </div>
          </div>

          {insights.map(insight => (
            <div key={insight.id} className="bg-white p-5 rounded-xl ring-1 ring-slate-200 shadow-sm hover:shadow-md transition-all duration-200 group hover-card-effect">
              <div className="flex justify-between items-start mb-3">
                <span className={`px-2.5 py-1 rounded-md text-[10px] font-bold uppercase tracking-wider
                  ${insight.severity === HealthStatus.CRITICAL ? 'bg-rose-50 text-rose-700 ring-1 ring-rose-100' : 
                    insight.severity === HealthStatus.WARNING ? 'bg-amber-50 text-amber-700 ring-1 ring-amber-100' : 'bg-blue-50 text-blue-700 ring-1 ring-blue-100'}
                `}>
                  {insight.type}
                </span>
                <span className="text-[10px] font-bold text-slate-400 bg-slate-50 px-2 py-1 rounded-full border border-slate-100">
                  {(insight.confidence * 100).toFixed(0)}% Conf.
                </span>
              </div>
              
              <h3 className="text-sm font-bold text-slate-800 mb-2 leading-snug group-hover:text-blue-700 transition-colors">{insight.title}</h3>
              <p className="text-xs text-slate-500 mb-5 leading-relaxed font-medium">{insight.description}</p>
              
              <button className="w-full flex items-center justify-between px-4 py-2.5 bg-white hover:bg-slate-50 text-slate-700 rounded-lg border border-slate-200 shadow-sm transition-all active:scale-95 btn-click-effect group-inner">
                <span className="text-xs font-bold tracking-wide">View Recommendation</span>
                <ArrowRight size={14} className="text-slate-400 group-inner-hover:translate-x-1 transition-transform group-inner-hover:text-blue-600" />
              </button>
            </div>
          ))}
        </div>
        
        <div className="p-4 border-t border-slate-100 bg-slate-50/50">
          <div className="flex flex-col items-center gap-2 text-center">
             <div className="flex items-center gap-2 text-[10px] font-bold text-slate-400 uppercase tracking-widest opacity-70">
                <ShieldCheck size={14} />
                <span>Audit Trail Enabled</span>
             </div>
             <p className="text-[9px] text-slate-400 font-medium max-w-[200px] leading-tight opacity-60">
                Visualization of data movement only. Not automated decision-making.
             </p>
          </div>
        </div>
      </div>
    </>
  );
};