import React from 'react';
import { InsightCard, HealthStatus } from '../types';
import { Lightbulb, ArrowRight, ShieldCheck, Zap, ChevronRight, PanelRightClose, PanelRightOpen, Eye } from 'lucide-react';

interface InsightPanelProps {
  insights: InsightCard[];
  isOpen: boolean;
  togglePanel: () => void;
}

export const InsightPanel: React.FC<InsightPanelProps> = ({ insights, isOpen, togglePanel }) => {
  return (
    <>
      {/* Toggle Button for when panel is closed */}
      {!isOpen && (
        <button
          onClick={togglePanel}
          className="absolute right-0 top-24 bg-slate-800 border-l border-t border-b border-slate-700 p-2 rounded-l-xl shadow-lg text-slate-400 hover:text-blue-400 hover:bg-slate-700 z-30 transition-all hover:pr-3 hover:shadow-blue-900/20"
          title="Open Insight Feed"
        >
          <PanelRightOpen size={20} />
        </button>
      )}

      <div
        className={`
          bg-slate-900/95 backdrop-blur-xl border-l border-slate-700/50 h-full flex flex-col flex-shrink-0 shadow-[-4px_0_40px_rgba(0,0,0,0.5)] z-20 transition-all duration-300 ease-in-out
          ${isOpen ? 'w-[400px] translate-x-0 opacity-100' : 'w-0 translate-x-full opacity-0 overflow-hidden'}
        `}
      >
        <div className="p-6 border-b border-slate-800/60 bg-slate-800/20 flex justify-between items-start">
          <div>
            <div className="flex items-center gap-2.5 mb-1.5">
              <div className="bg-amber-500/10 p-2 rounded-lg text-amber-500 ring-1 ring-amber-500/20 shadow-[0_0_15px_rgba(245,158,11,0.1)]">
                <Lightbulb size={18} className="fill-amber-500/50" />
              </div>
              <h2 className="font-bold text-white text-lg tracking-tight">Insight Feed</h2>
            </div>
            <p className="text-xs text-slate-400 font-medium pl-1">Prioritized items for review</p>
          </div>
          <button
            onClick={togglePanel}
            className="text-slate-500 hover:text-white hover:bg-white/10 p-2 rounded-lg transition-colors active:scale-95"
          >
            <PanelRightClose size={18} />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-6 space-y-5 bg-transparent custom-scrollbar">
          {/* Disclaimer Card */}
          <div className="bg-blue-900/20 border border-blue-500/30 rounded-lg p-3 flex gap-3">
            <div className="mt-0.5"><Eye size={14} className="text-blue-400" /></div>
            <div>
              <p className="text-[10px] text-blue-200 font-medium leading-tight">
                <span className="font-bold text-blue-100">Human-in-the-Loop:</span> All insights generated by the system are recommendations intended for human review and decision-making.
              </p>
            </div>
          </div>

          {insights.map(insight => (
            <div key={insight.id} className="bg-slate-800/40 p-5 rounded-xl ring-1 ring-white/10 shadow-lg hover:ring-blue-500/30 hover:bg-slate-800/60 transition-all duration-200 group hover-card-effect backdrop-blur-sm">
              <div className="flex justify-between items-start mb-3">
                <span className={`px-2.5 py-1 rounded-md text-[10px] font-bold uppercase tracking-wider
                  ${insight.severity === HealthStatus.CRITICAL ? 'bg-rose-500/10 text-rose-400 ring-1 ring-rose-500/20' :
                    insight.severity === HealthStatus.WARNING ? 'bg-amber-500/10 text-amber-400 ring-1 ring-amber-500/20' : 'bg-blue-500/10 text-blue-400 ring-1 ring-blue-500/20'}
                `}>
                  {insight.type}
                </span>
                <span className="text-[10px] font-bold text-slate-400 bg-slate-900/50 px-2 py-1 rounded-full border border-white/5">
                  {(insight.confidence * 100).toFixed(0)}% Conf.
                </span>
              </div>

              <h3 className="text-sm font-bold text-slate-200 mb-2 leading-snug group-hover:text-blue-300 transition-colors">{insight.title}</h3>
              <p className="text-xs text-slate-400 mb-5 leading-relaxed font-medium">{insight.description}</p>

              <button className="w-full flex items-center justify-between px-4 py-2.5 bg-slate-900 hover:bg-slate-800 text-slate-300 rounded-lg border border-slate-700 shadow-sm transition-all active:scale-95 btn-click-effect group-inner hover:text-white hover:border-slate-600">
                <span className="text-xs font-bold tracking-wide">View Recommendation</span>
                <ArrowRight size={14} className="text-slate-500 group-inner-hover:translate-x-1 transition-transform group-inner-hover:text-blue-400" />
              </button>
            </div>
          ))}
        </div>

        <div className="p-4 border-t border-slate-800/60 bg-slate-900/50">
          <div className="flex flex-col items-center gap-2 text-center">
            <div className="flex items-center gap-2 text-[10px] font-bold text-slate-600 uppercase tracking-widest opacity-70">
              <ShieldCheck size={14} />
              <span>Audit Trail Enabled</span>
            </div>
            <p className="text-[9px] text-slate-600 font-medium max-w-[200px] leading-tight opacity-50">
              Visualization of data movement only. Not automated decision-making.
            </p>
          </div>
        </div>
      </div>
    </>
  );
};